# Generated by Django 5.2.3 on 2025-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumappuser',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
